# Generated by Django 5.2.12 on 2026-04-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_avaliacao_comentario_avaliacao_data_postagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(related_name='filmes', to='app.genero'),
        ),
        migrations.AlterField(
            model_name='ator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='realizador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
